разбила все на компоненты
gloomy-onion/Pizza pull request #1
Opened 2023-10-09 17:33 UTC by gloomy-onion

2023-10-10 13:13 UTC, Alterqq reviewed
Критов нет, оставил пару комментов

2023-10-10 13:13 UTC, Alterqq commented on src/App.module.scss
> +  h2 {
стили на теги - плохо. Лучше рулить классами

2023-10-10 13:13 UTC, Alterqq commented on src/Sort/Sort.jsx
> +        <img src={sortLabel} alt={'Sort label'}/>
Эт через цсс надо сделать

2023-10-10 15:36 UTC, gloomy-onion commented on src/Sort/Sort.jsx
> +        <img src={sortLabel} alt={'Sort label'}/>
треугольник нарисовать через цсс

2023-10-11 14:54 UTC, Alterqq requested changes

2023-10-11 14:54 UTC, Alterqq commented on test.js
> +class PizzasManager {
Это нам не надо)

2023-10-11 14:54 UTC, Alterqq commented on src/Sort/Sort.jsx
> +        <div className={styles.sortLabel}> </div>
в данном случае тег самозакрывающийся, тк в нем нет контента

2023-10-12 20:30 UTC, Alterqq approved these changes

2023-10-12 20:31 UTC, merged