Lesson78
gloomy-onion/Pizza pull request #3
Opened 2023-10-31 10:51 UTC by gloomy-onion

2023-10-31 15:56 UTC, Alterqq requested changes

2023-10-31 15:56 UTC, Alterqq commented on src/MainContent/MainContent.jsx
> +    fetch(`https://64c7f223a1fe0128fbd57bb6.mockapi.io/pizza?
Вынести урл в константы

2023-10-31 15:56 UTC, Alterqq commented on src/MainContent/MainContent.jsx
> +            ? [...new Array(6)].map((_, index) => <Skeleton key={index}/>)
Скелетон - отдельный компонент

2023-10-31 15:56 UTC, Alterqq commented on src/Sort/Sort.jsx
> +  const list = [
вынести в константы

2023-10-31 15:56 UTC, Alterqq commented on src/Sort/Sort.jsx
> +          {list.map((obj, i) => (
нейминг переменых

2023-11-01 07:15 UTC, Alterqq commented on src/common/constants.js
> +export const sortList = [
Это все же не в common должно лежать
а в src/Sort/constants.ts

2023-11-01 07:15 UTC, Alterqq commented on src/Cart/Cart.jsx
> +                <a href="/src/pages" className={cn(styles.button, styles.goBackBtn)}>
А эт че такое?)

2023-11-01 07:18 UTC, gloomy-onion commented on src/Cart/Cart.jsx
> +                <a href="/src/pages" className={cn(styles.button, styles.goBackBtn)}>
Ой а это говно какое то вылезла, исправлю

2023-11-01 07:23 UTC, Alterqq commented on src/Cart/Cart.jsx
> +                <a href="/src/pages" className={cn(styles.button, styles.goBackBtn)}>
Там, наверное, имелось в виду <Link>, а не <a>?

2023-11-01 12:40 UTC, Alterqq approved these changes

2023-11-01 12:41 UTC, merged